### ISSUE TITLE
your computer restarted because of a problem press a key or wait a few seconds vmware

### ISSUE THREAD

**Issue by JkD004** [paolo-projects/auto-unlocker#113]
Unlocker 3.0.2 for VMware Workstation
=====================================
(c) Dave Parsons 2011-18

Set encoding parameters...
Active code page: 850

VMware is installed at: C:\Program Files (x86)\VMware\VMware Workstation\
VMware product version: 17.0.0.20800274

Stopping VMware services...

Backing up files...
C:\Program Files (x86)\VMware\VMware Workstation\x64\vmware-vmx.exe -> C:\Users\Downloads\release-python-embedded\backup\x64\vmware-vmx.exe
1 File(s) copied
C:\Program Files (x86)\VMware\VMware Workstation\x64\vmware-vmx-debug.exe -> C:\Users\Downloads\release-python-embedded\backup\x64\vmware-vmx-debug.exe
1 File(s) copied
C:\Program Files (x86)\VMware\VMware Workstation\x64\vmware-vmx-stats.exe -> C:\Users\Downloads\release-python-embedded\backup\x64\vmware-vmx-stats.exe
1 File(s) copied
C:\Program Files (x86)\VMware\VMware Workstation\vmwarebase.dll -> C:\Users\Downloads\release-python-embedded\backup\vmwarebase.dll
1 File(s) copied

Patching...
File: C:\Program Files (x86)\VMware\VMware Workstation\x64\vmware-vmx.exe

appleSMCTableV0 (smc.version = "0")
appleSMCTableV0 Address      : 0xcd6300
appleSMCTableV0 Private Key #: 0xF2/242
appleSMCTableV0 Public Key  #: 0xF0/240
appleSMCTableV0 Table        : 0xcd6320
+LKS Key:
002 0xcd6368 +LKS 01 flag 0x90 0x1401f8ec0 07
OSK0 Key Before:
241 0xcda6a0 OSK0 32 ch8* 0x80 0x1401f8ec0 6F 75 72 68 61 72 64 77 6F 72 6B 62 79 74 68 65 73 65 77 6F 72 64 73 67 75 61 72 64 65 64 70 6C
OSK0 Key After:
241 0xcda6a0 OSK0 32 ch8* 0x80 0x1401f8ec0 6F 75 72 68 61 72 64 77 6F 72 6B 62 79 74 68 65 73 65 77 6F 72 64 73 67 75 61 72 64 65 64 70 6C
OSK1 Key Before:
242 0xcda6e8 OSK1 32 ch8* 0x80 0x1401f8ec0 65 61 73 65 64 6F 6E 74 73 74 65 61 6C 28 63 29 41 70 70 6C 65 43 6F 6D 70 75 74 65 72 49 6E 63
OSK1 Key After:
242 0xcda6e8 OSK1 32 ch8* 0x80 0x1401f8ec0 65 61 73 65 64 6F 6E 74 73 74 65 61 6C 28 63 29 41 70 70 6C 65 43 6F 6D 70 75 74 65 72 49 6E 63

appleSMCTableV1 (smc.version = "1")
appleSMCTableV1 Address      : 0xcda730
appleSMCTableV1 Private Key #: 0x01B4/436
appleSMCTableV1 Public Key  #: 0x01B0/432
appleSMCTableV1 Table        : 0xcda750
+LKS Key:
004 0xcda828 +LKS 01 flag 0x90 0x1401f8ec0 01
OSK0 Key Before:
435 0xce2160 OSK0 32 ch8* 0x90 0x1401f8ec0 6F 75 72 68 61 72 64 77 6F 72 6B 62 79 74 68 65 73 65 77 6F 72 64 73 67 75 61 72 64 65 64 70 6C
OSK0 Key After:
435 0xce2160 OSK0 32 ch8* 0x90 0x1401f8ec0 6F 75 72 68 61 72 64 77 6F 72 6B 62 79 74 68 65 73 65 77 6F 72 64 73 67 75 61 72 64 65 64 70 6C
OSK1 Key Before:
436 0xce21a8 OSK1 32 ch8* 0x90 0x1401f8ec0 65 61 73 65 64 6F 6E 74 73 74 65 61 6C 28 63 29 41 70 70 6C 65 43 6F 6D 70 75 74 65 72 49 6E 63
OSK1 Key After:
436 0xce21a8 OSK1 32 ch8* 0x90 0x1401f8ec0 65 61 73 65 64 6F 6E 74 73 74 65 61 6C 28 63 29 41 70 70 6C 65 43 6F 6D 70 75 74 65 72 49 6E 63

File: C:\Program Files (x86)\VMware\VMware Workstation\x64\vmware-vmx-debug.exe

appleSMCTableV0 (smc.version = "0")
appleSMCTableV0 Address      : 0xf99010
appleSMCTableV0 Private Key #: 0xF2/242
appleSMCTableV0 Public Key  #: 0xF0/240
appleSMCTableV0 Table        : 0xf99030
+LKS Key:
002 0xf99078 +LKS 01 flag 0x90 0x140273520 07
OSK0 Key Before:
241 0xf9d3b0 OSK0 32 ch8* 0x80 0x140273520 6F 75 72 68 61 72 64 77 6F 72 6B 62 79 74 68 65 73 65 77 6F 72 64 73 67 75 61 72 64 65 64 70 6C
OSK0 Key After:
241 0xf9d3b0 OSK0 32 ch8* 0x80 0x140273520 6F 75 72 68 61 72 64 77 6F 72 6B 62 79 74 68 65 73 65 77 6F 72 64 73 67 75 61 72 64 65 64 70 6C
OSK1 Key Before:
242 0xf9d3f8 OSK1 32 ch8* 0x80 0x140273520 65 61 73 65 64 6F 6E 74 73 74 65 61 6C 28 63 29 41 70 70 6C 65 43 6F 6D 70 75 74 65 72 49 6E 63
OSK1 Key After:
242 0xf9d3f8 OSK1 32 ch8* 0x80 0x140273520 65 61 73 65 64 6F 6E 74 73 74 65 61 6C 28 63 29 41 70 70 6C 65 43 6F 6D 70 75 74 65 72 49 6E 63

appleSMCTableV1 (smc.version = "1")
appleSMCTableV1 Address      : 0xf9d440
appleSMCTableV1 Private Key #: 0x01B4/436
appleSMCTableV1 Public Key  #: 0x01B0/432
appleSMCTableV1 Table        : 0xf9d460
+LKS Key:
004 0xf9d538 +LKS 01 flag 0x90 0x140273520 01
OSK0 Key Before:
435 0xfa4e70 OSK0 32 ch8* 0x90 0x140273520 6F 75 72 68 61 72 64 77 6F 72 6B 62 79 74 68 65 73 65 77 6F 72 64 73 67 75 61 72 64 65 64 70 6C
OSK0 Key After:
435 0xfa4e70 OSK0 32 ch8* 0x90 0x140273520 6F 75 72 68 61 72 64 77 6F 72 6B 62 79 74 68 65 73 65 77 6F 72 64 73 67 75 61 72 64 65 64 70 6C
OSK1 Key Before:
436 0xfa4eb8 OSK1 32 ch8* 0x90 0x140273520 65 61 73 65 64 6F 6E 74 73 74 65 61 6C 28 63 29 41 70 70 6C 65 43 6F 6D 70 75 74 65 72 49 6E 63
OSK1 Key After:
436 0xfa4eb8 OSK1 32 ch8* 0x90 0x140273520 65 61 73 65 64 6F 6E 74 73 74 65 61 6C 28 63 29 41 70 70 6C 65 43 6F 6D 70 75 74 65 72 49 6E 63

File: C:\Program Files (x86)\VMware\VMware Workstation\x64\vmware-vmx-stats.exe

appleSMCTableV0 (smc.version = "0")
appleSMCTableV0 Address      : 0xd32a30
appleSMCTableV0 Private Key #: 0xF2/242
appleSMCTableV0 Public Key  #: 0xF0/240
appleSMCTableV0 Table        : 0xd32a50
+LKS Key:
002 0xd32a98 +LKS 01 flag 0x90 0x140208340 07
OSK0 Key Before:
241 0xd36dd0 OSK0 32 ch8* 0x80 0x140208340 6F 75 72 68 61 72 64 77 6F 72 6B 62 79 74 68 65 73 65 77 6F 72 64 73 67 75 61 72 64 65 64 70 6C
OSK0 Key After:
241 0xd36dd0 OSK0 32 ch8* 0x80 0x140208340 6F 75 72 68 61 72 64 77 6F 72 6B 62 79 74 68 65 73 65 77 6F 72 64 73 67 75 61 72 64 65 64 70 6C
OSK1 Key Before:
242 0xd36e18 OSK1 32 ch8* 0x80 0x140208340 65 61 73 65 64 6F 6E 74 73 74 65 61 6C 28 63 29 41 70 70 6C 65 43 6F 6D 70 75 74 65 72 49 6E 63
OSK1 Key After:
242 0xd36e18 OSK1 32 ch8* 0x80 0x140208340 65 61 73 65 64 6F 6E 74 73 74 65 61 6C 28 63 29 41 70 70 6C 65 43 6F 6D 70 75 74 65 72 49 6E 63

appleSMCTableV1 (smc.version = "1")
appleSMCTableV1 Address      : 0xd36e60
appleSMCTableV1 Private Key #: 0x01B4/436
appleSMCTableV1 Public Key  #: 0x01B0/432
appleSMCTableV1 Table        : 0xd36e80
+LKS Key:
004 0xd36f58 +LKS 01 flag 0x90 0x140208340 01
OSK0 Key Before:
435 0xd3e890 OSK0 32 ch8* 0x90 0x140208340 6F 75 72 68 61 72 64 77 6F 72 6B 62 79 74 68 65 73 65 77 6F 72 64 73 67 75 61 72 64 65 64 70 6C
OSK0 Key After:
435 0xd3e890 OSK0 32 ch8* 0x90 0x140208340 6F 75 72 68 61 72 64 77 6F 72 6B 62 79 74 68 65 73 65 77 6F 72 64 73 67 75 61 72 64 65 64 70 6C
OSK1 Key Before:
436 0xd3e8d8 OSK1 32 ch8* 0x90 0x140208340 65 61 73 65 64 6F 6E 74 73 74 65 61 6C 28 63 29 41 70 70 6C 65 43 6F 6D 70 75 74 65 72 49 6E 63
OSK1 Key After:
436 0xd3e8d8 OSK1 32 ch8* 0x90 0x140208340 65 61 73 65 64 6F 6E 74 73 74 65 61 6C 28 63 29 41 70 70 6C 65 43 6F 6D 70 75 74 65 72 49 6E 63

GOS Patching: C:\Program Files (x86)\VMware\VMware Workstation\vmwarebase.dll
Traceback (most recent call last):
  File "C:\Users\Downloads\release-python-embedded\unlocker.py", line 401, in <module>
    main()
  File "C:\Users\Downloads\release-python-embedded\unlocker.py", line 397, in main
    patchbase(vmwarebase)
  File "C:\Users\Downloads\release-python-embedded\unlocker.py", line 306, in patchbase
    f = open(name, 'r+b')
PermissionError: [Errno 13] Permission denied: 'C:\\Program Files (x86)\\VMware\\VMware Workstation\\vmwarebase.dll'

**Comment by Kasherpete** [comment]
I fixed this by closing VMware.... lol I felt dumb at that moment. Also make sure you run as admin

**Comment by Geylen** [comment]
пытался поставить секвоя все круто но такая ошибка вылазиет,думаю ладно попробую сонома, но увы вроде анлокер поставил все вроде прошло норм но нехочет зараза работать
