### ISSUE TITLE
not installing any thing in vmware 16

### ISSUE THREAD

**Issue by bossmukul** [paolo-projects/auto-unlocker#75]
GOS Patching: C:\Program Files (x86)\VMware\VMware Workstation\vmwarebase.dll
Traceback (most recent call last):
  File "C:\Users\bossM\Desktop\unlocker\unlocker.py", line 401, in <module>
    main()
  File "C:\Users\bossM\Desktop\unlocker\unlocker.py", line 397, in main
    patchbase(vmwarebase)
  File "C:\Users\bossM\Desktop\unlocker\unlocker.py", line 306, in patchbase
    f = open(name, 'r+b')
PermissionError: [Errno 13] Permission denied: 'C:\\Program Files (x86)\\VMware\\VMware Workstation\\vmwarebase.dll'

**Comment by lcy19** [comment]
seems like permission error, try run it using  administrator privileges，for example, right click and choose
